<?php
return array(
  'WEBSITE_NAME'    =>    '特房网',
  'PAGES'   =>    '25',
  'LIMIT'   =>    '10',
  // 户型
  'HTYPE'   =>  array(
        '0'=>
             array(
               'id'=>'1',
               'name'=>"一室"
  ),
       '1'=>
             array(
               'id'=>'2',
               'name'=>"二室"
  ),
        '2'=>
             array(
               'id'=>'3',
               'name'=>"三室"
  ),
        '3'=>
             array(
               'id'=>'4',
               'name'=>"四室"
  ),
        '4'=>
             array(
               'id'=>'5',
               'name'=>"五室以上"
  )

     
  ),
  // 产权类型
  'PRTYPE'  =>  array(
       '0'=>
             array(
               'id'=>'1',
               'name'=>"回迁房"
  ),
       '1'=>
             array(
               'id'=>'2',
               'name'=>"军产房"
  ),
        '2'=>
             array(
               'id'=>'3',
               'name'=>"法拍房"
  ),
        '3'=>
             array(
               'id'=>'4',
               'name'=>"福利房"
  ),
        '4'=>
             array(
               'id'=>'5',
               'name'=>"小产权房"
  ),
        '5'=>
             array(
               'id'=>'6',
               'name'=>"其他"
  )
      
  ),
  // 房屋类型
  'HOUSE_TYPE'  =>  array(
     '0'=>
             array(
               'id'=>'1',
               'name'=>"期房"
  ),
       '1'=>
             array(
               'id'=>'2',
               'name'=>"代售"
  ),
        '2'=>
             array(
               'id'=>'3',
               'name'=>"现房"
  ),
        '3'=>
             array(
               'id'=>'4',
               'name'=>"尾盘"
  ),
        '4'=>
             array(
               'id'=>'5',
               'name'=>"其他"
  )
     
  ),
  // 物业类型
  'PTYPE'   =>  array(
         '0'=>
             array(
               'id'=>'1',
               'name'=>"普通住宅"
  ),
       '1'=>
             array(
               'id'=>'2',
               'name'=>"公寓"
  ),
        '2'=>
             array(
               'id'=>'3',
               'name'=>"花园式洋房"
  ),
        '3'=>
             array(
               'id'=>'4',
               'name'=>"酒店式公寓"
  ),
        '4'=>
             array(
               'id'=>'5',
               'name'=>"商住两用"
  ),
        '5'=>
             array(
               'id'=>'6',
               'name'=>"别野"
  ),
         '6'=>
             array(
               'id'=>'7',
               'name'=>"写字楼"
  ),
        '7'=>
             array(
               'id'=>'8',
               'name'=>"商铺"
  ),
        '8'=>
             array(
               'id'=>'9',
               'name'=>"其他"
  )
      
  ),
  //价格
  'PRICE'   =>  array(
       '0'=>
             array(
               'id'=>'1',
               'name'=>"6千以下"
  ),
       '1'=>
             array(
               'id'=>'2',
               'name'=>"6千-1万"
  ),
        '2'=>
             array(
               'id'=>'3',
               'name'=>"1-1.5万"
  ),
        '3'=>
             array(
               'id'=>'4',
               'name'=>"1.5-2万"
  ),
        '4'=>
             array(
               'id'=>'5',
               'name'=>"2-3万"
  ),
        '5'=>
             array(
               'id'=>'6',
               'name'=>"3-4万"
  ),
         '6'=>
             array(
               'id'=>'7',
               'name'=>"4-6万"
  ),
        '7'=>
             array(
               'id'=>'8',
               'name'=>"6万以上"
  )

    ),
   // 面积
  'AREA'   =>  array(
         '0'=>
             array(
               'id'=>'1',
               'name'=>"60以下"
  ),
       '1'=>
             array(
               'id'=>'2',
               'name'=>"60-80"
  ),
        '2'=>
             array(
               'id'=>'3',
               'name'=>"80-100"
  ),
        '3'=>
             array(
               'id'=>'4',
               'name'=>"100-120"
  ),
        '4'=>
             array(
               'id'=>'5',
               'name'=>"120-150"
  ),
        '5'=>
             array(
               'id'=>'6',
               'name'=>"150-200"
  ),
         '6'=>
             array(
               'id'=>'7',
               'name'=>"200以上"
  ),
      
  )
);